version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      - dev-bashhistory:/commandhistory

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mqtt

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    # environment:

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mqtt:
    image: eclipse-mosquitto:2.0.9
    restart: unless-stopped
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  loki:
    image: grafana/loki:2.5.0
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: service:mqtt

  grafana:
    image: grafana/grafana:8.5.2
    network_mode: service:mqtt

volumes:
  mqtt-data:
  dev-bashhistory: